# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Chair_pb2 as Chair__pb2


class ChairServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ChairUpdate = channel.unary_unary(
        '/ChairService/ChairUpdate',
        request_serializer=Chair__pb2.Chair.SerializeToString,
        response_deserializer=Chair__pb2.ChairResponse.FromString,
        )


class ChairServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ChairUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChairServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ChairUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.ChairUpdate,
          request_deserializer=Chair__pb2.Chair.FromString,
          response_serializer=Chair__pb2.ChairResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ChairService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
