from enum import Enum

GRPC_VERSION = 1
GRPC_SERVER_IP = "localhost:50051"

SERIAL_VERSION = 1
SERIAL_BAUDRATE = 38400

SERIAL_READ_START = 0xAF
SERIAL_READ_END = 0xFE

SERIAL_SEND_START = 0xDE
SERIAL_SEND_END = 0xED

class SerialHeader(Enum):
	DEBUG = 0
	DISTANCE = 1
	PRESSURE_BACK = 2
	PRESSURE_SEAT = 3
	TEMPERATURE = 4

class SerialDispatchError(Enum):
	NO_TERMINATION_BYTE = 1
	CHECKSUM_ERROR = 2
	VERSION_ERROR = 3
	CALLBACK_FUNCTION_NOT_EXISTENT = 4
