# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chair.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chair.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x63hair.proto\"[\n\x10\x43hairInformation\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x13\n\x0bsensor_type\x18\x03 \x01(\x05\x12\x0e\n\x06values\x18\x04 \x01(\t\" \n\rChairResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x42\n\x0c\x43hairService\x12\x32\n\x0b\x43hairUpdate\x12\x11.ChairInformation\x1a\x0e.ChairResponse\"\x00\x62\x06proto3')
)




_CHAIRINFORMATION = _descriptor.Descriptor(
  name='ChairInformation',
  full_name='ChairInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ChairInformation.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ChairInformation.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_type', full_name='ChairInformation.sensor_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='ChairInformation.values', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=106,
)


_CHAIRRESPONSE = _descriptor.Descriptor(
  name='ChairResponse',
  full_name='ChairResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ChairResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['ChairInformation'] = _CHAIRINFORMATION
DESCRIPTOR.message_types_by_name['ChairResponse'] = _CHAIRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChairInformation = _reflection.GeneratedProtocolMessageType('ChairInformation', (_message.Message,), dict(
  DESCRIPTOR = _CHAIRINFORMATION,
  __module__ = 'chair_pb2'
  # @@protoc_insertion_point(class_scope:ChairInformation)
  ))
_sym_db.RegisterMessage(ChairInformation)

ChairResponse = _reflection.GeneratedProtocolMessageType('ChairResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHAIRRESPONSE,
  __module__ = 'chair_pb2'
  # @@protoc_insertion_point(class_scope:ChairResponse)
  ))
_sym_db.RegisterMessage(ChairResponse)



_CHAIRSERVICE = _descriptor.ServiceDescriptor(
  name='ChairService',
  full_name='ChairService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=142,
  serialized_end=208,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChairUpdate',
    full_name='ChairService.ChairUpdate',
    index=0,
    containing_service=None,
    input_type=_CHAIRINFORMATION,
    output_type=_CHAIRRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAIRSERVICE)

DESCRIPTOR.services_by_name['ChairService'] = _CHAIRSERVICE

# @@protoc_insertion_point(module_scope)
