# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chair_pb2 as chair__pb2


class ChairServiceStub(object):
  """
  class GRPCHeader(Enum):
  DEBUG = 0
  DISTANCE = 1
  PRESSURE_BACK = 2
  PRESSURE_SEAT = 3
  TEMPERATURE = 4
  GYROSCOPE = 5

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ChairUpdate = channel.unary_unary(
        '/ChairService/ChairUpdate',
        request_serializer=chair__pb2.ChairInformation.SerializeToString,
        response_deserializer=chair__pb2.ChairResponse.FromString,
        )


class ChairServiceServicer(object):
  """
  class GRPCHeader(Enum):
  DEBUG = 0
  DISTANCE = 1
  PRESSURE_BACK = 2
  PRESSURE_SEAT = 3
  TEMPERATURE = 4
  GYROSCOPE = 5

  """

  def ChairUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChairServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ChairUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.ChairUpdate,
          request_deserializer=chair__pb2.ChairInformation.FromString,
          response_serializer=chair__pb2.ChairResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ChairService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
